create table DOCTOR
(
    ID             BIGINT generated by default as
        IDENTITY (start with 1 increment by 1)
        constraint DOCTOR_PK
            primary key,
    FIRST_NAME     VARCHAR(30) not null,
    LAST_NAME      VARCHAR(30) not null,
    MIDDLE_NAME    VARCHAR(30),
    SPECIALIZATION VARCHAR(30) not null
);

create table PATIENT
(
    ID           BIGINT generated by default as
        IDENTITY (start with 1 increment by 1)
        constraint PATIENT_PK
            primary key,
    FIRST_NAME   VARCHAR(30) not null,
    LAST_NAME    VARCHAR(30) not null,
    MIDDLE_NAME  VARCHAR(30),
    PHONE_NUMBER VARCHAR(15) not null
);

create table RECIPE
(
    ID            BIGINT generated by default as
        IDENTITY (start with 1 increment by 1)
        primary key,
    DESCRIPTION   VARCHAR(300) not null,
    PATIENT       BIGINT
        constraint PATIENT
            references PATIENT,
    DOCTOR        BIGINT
        constraint DOCTOR
            references DOCTOR,
    CREATION_DATE DATE         not null,
    VALIDITY      DATE         not null,
    PRIORITY      VARCHAR(6)   not null
);